### ISSUE TITLE
Fullscreen setting doesn't affect home page

### ISSUE THREAD

**Issue by navzam** [kipr/botui#18]
The fullscreen setting affects every page except the home page because we never call present() on the home page. It always exists at the bottom of the stack.

**Comment by Zacharyprime** [comment]
This got fixed a long time ago and was an issue during the development of the Wallaby (based off the date it was posted). The Wombat does not have this issue and if it does somehow exist in edge cases on the Wallaby, it has not presented itself as an issue from a customer.
