### ISSUE TITLE
Can't maximize UI after minimizing

### ISSUE THREAD

**Issue by navzam** [kipr/botui#19]
Clicking "Hide UI" in settings minimizes botui, but the top-left arrow disappears, so we can't switch back to botui.

**Comment by prithvirajkadiyala** [comment]
I switched the User Interface to the lxterminal which shows us desktop mode like the windows and there we are able to click on the minimized tab of BOTUI to get it back to displaying.

**Comment by prithvirajkadiyala** [comment]
Auto-hiding the taskbar because it is visible when dialog box for text input is open.

**Comment by prithvirajkadiyala** [comment]
There is also a shortcut created on the homepage/Desktop of the Pi which will allow starting the service again by the User without having to restart the device.
