### ISSUE TITLE
Battery logic for all devices

### ISSUE THREAD

**Issue by navzam** [kipr/botui#20]
The battery logic added to support different battery types should be general to all devices, not specific to the wallaby device. All devices should support functions like `supportedBatteryTypes()` and `batteryType()`

**Comment by Zacharyprime** [comment]
This doesn't really make sense in the current structure of botui.

The term "wallaby" has in a way been altered (in software) to basically mean all future controllers after the wallaby.
To fix this we would have to do a complete change all the references to the "wallaby" device every time we make a new controller.

The wombat as far as software/hardware development is concerned, can be thought of as the Wallaby V2.
If this is not desirable to future developers (or Raj), then I suggest we change everything to wombat, and keep it.

I don't think we have plans to move away from the Wombat in 4 years as was the case with previous controllers, but updates and revisions to the Wombat.
(This is what Steve, as of writing this, is aiming for)
