### ISSUE TITLE
A,B,C Buttons off screen

### ISSUE THREAD

**Issue by aborgerding** [kipr/botui#54]
From Charles - The ABC buttons for a running program are too low on the screen to fully display

This doesn't seem to be an issue on our end. Attaching images showing what we see from the controller. Awaiting additional feedback from Charles. 

These images are from 24.8:
![IMG_9501](https://user-images.githubusercontent.com/35960368/64645028-956fb200-d3d9-11e9-958b-a24249398f4d.JPG)
![IMG_1278](https://user-images.githubusercontent.com/35960368/64645030-956fb200-d3d9-11e9-899a-d749d7cb9425.JPG)

**Comment by aborgerding** [comment]
Charles - Here they are.  It appears the title bar is pushing them down.  I took these after a reboot to make sure the effect isn't a leftover.  When I get a chance I'll do a fresh image to see if it persists, which if so would indicate something is amiss with my particular Wombat.

![20190910_172850_resized](https://user-images.githubusercontent.com/35960368/64653278-a88b7d80-d3eb-11e9-956d-a8e0d751f706.jpg)
![20190910_172810](https://user-images.githubusercontent.com/35960368/64653280-a88b7d80-d3eb-11e9-9326-5cc64c4b79e6.jpg)

Potentially result of previous testing. Waiting to see update from Charles after refresh.

**Comment by Zacharyprime** [comment]
This issue has not been present in production yet and appears to have only been a problem in the development stage (or if the user is messing around with Debian desktop controls). I think this was just an issue with Charles' Debian settings or his image but the current standard image does not have this issue.

If somebody is able to recreate this issue and show any of the active developers, we can reopen it.
