### ISSUE TITLE
Add "Reflash Button"

### ISSUE THREAD

**Issue by Zacharyprime** [kipr/botui#60]
The DMA De-synchronized error is common enough that it is a hassle to explain to customers over the phone how to navigate to the terminal and reflash or do an entire update to fix the issue.

It would also benefit lab staff that repair them as we could just press a button to solve the issue in seconds.

Anywhere on the UI there should probably be a button that calls reflash since it isn't harmful to do so when unnecessary.

**Comment by prithvirajkadiyala** [comment]
Sure, we can do that

**Comment by Zacharyprime** [comment]
There is already a button in place for doing this, we just need to get it working
