### ISSUE TITLE
QT5 Support

### ISSUE THREAD

**Issue by justinmerrell** [kipr/botui#70]
Should this be QT5? It halts the install process using only QT5 otherwise. 

https://github.com/kipr/botui/blob/be9c174f4508cc73787fee84823089437eaa4203/CMakeLists.txt#L42

**Comment by Zacharyprime** [comment]
Botui is currently done in Qt4, we are working on updating botui to Qt5 (and then hopefully Qt6).

Here is the original issue message: https://github.com/kipr/botui/issues/67

Here is the PR associated with the software, I might try to setup a separate branch on this repo for it: https://github.com/kipr/botui/pull/73
